pr:
  branches:
    include: 
    - main

parameters:
  - name: ENABLE_DEPLOY_K8
    type: boolean
    displayName: Enable automatically deploy to OCI Kubernetes
    default: false
    
  - name: CLUSTER_TYPE
    type: string
    default: AWS
    displayName: Choose the Cluster Type
    values: 
    - OCI
    - AWS

  - name: branch
    type: string
    default: 'main'
  - name: environment
    type: string
    default: 'dev'

jobs:
  - job: build
    displayName: 'Build and Test'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: git --version
          
        displayName: 'Build and Test'

  - job: deploy
    displayName: 'Deploy to $(environment)'
    dependsOn: build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/$(branch)'))
    steps:
      - script: echo 'Deploying the code to $(environment)...'
        displayName: 'Deploy to $(environment)'
# Test
